# Generated by Django 4.1.7 on 2023-08-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=20)),
                ('number', models.IntegerField(max_length=8)),
                ('email', models.CharField(max_length=20)),
                ('amount', models.IntegerField(max_length=2)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
