# Generated by Django 4.1.7 on 2023-08-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_coustomer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustomer',
            name='UserNum',
            field=models.CharField(max_length=8, verbose_name='رقم الهاتف'),
        ),
    ]
