# Generated by Django 4.1.7 on 2023-08-18 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_coustomer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coustomer',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='coustomer',
            name='Amount',
            field=models.IntegerField(default='00', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='السعر'),
        ),
    ]
