# Generated by Django 4.1.7 on 2023-08-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_coustomer_date_alter_coustomer_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coustomer',
            name='date',
        ),
        migrations.AlterField(
            model_name='coustomer',
            name='Time',
            field=models.DateTimeField(max_length=20, null=True, verbose_name='التاريخ و الوقت'),
        ),
    ]
