# Generated by Django 4.1.7 on 2023-08-18 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_coustomer_pymentway_alter_coustomer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustomer',
            name='PymentWay',
            field=models.CharField(default='visa', help_text='Visa او chash', max_length=20, verbose_name='طريقه الدفع'),
        ),
        migrations.AlterField(
            model_name='coustomer',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 17, 28, 25, 218066), max_length=20, null=True, unique=True, verbose_name='التاريخ و الوقت'),
        ),
        migrations.AlterField(
            model_name='coustomer',
            name='UserNum',
            field=models.CharField(help_text='+رقم الهاتف 968', max_length=8, verbose_name='رقم الهاتف'),
        ),
    ]
