# Generated by Django 4.1.7 on 2023-08-19 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_appointment_alter_coustomer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustomer',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 0, 35, 17, 842833), max_length=20, null=True, verbose_name='التاريخ و الوقت'),
        ),
    ]
