# Generated by Django 4.1.7 on 2023-08-19 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_coustomer_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AlterField(
            model_name='coustomer',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 1, 29, 38, 644889), max_length=20, null=True, verbose_name='التاريخ و الوقت'),
        ),
    ]
